// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modularPlatform.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	modularPlatform.proto

It has these top-level messages:
	Module
	Details
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Module struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	Location   string `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	RunCommand string `protobuf:"bytes,4,opt,name=runCommand" json:"runCommand,omitempty"`
}

func (m *Module) Reset()                    { *m = Module{} }
func (m *Module) String() string            { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()               {}
func (*Module) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Module) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Module) GetRunCommand() string {
	if m != nil {
		return m.RunCommand
	}
	return ""
}

type Details struct {
	Details string `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
}

func (m *Details) Reset()                    { *m = Details{} }
func (m *Details) String() string            { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()               {}
func (*Details) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Details) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*Module)(nil), "server.Module")
	proto.RegisterType((*Details)(nil), "server.Details")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Platform service

type PlatformClient interface {
	RegisterModule(ctx context.Context, in *Module, opts ...grpc.CallOption) (*Details, error)
}

type platformClient struct {
	cc *grpc.ClientConn
}

func NewPlatformClient(cc *grpc.ClientConn) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) RegisterModule(ctx context.Context, in *Module, opts ...grpc.CallOption) (*Details, error) {
	out := new(Details)
	err := grpc.Invoke(ctx, "/server.Platform/RegisterModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Platform service

type PlatformServer interface {
	RegisterModule(context.Context, *Module) (*Details, error)
}

func RegisterPlatformServer(s *grpc.Server, srv PlatformServer) {
	s.RegisterService(&_Platform_serviceDesc, srv)
}

func _Platform_RegisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Module)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).RegisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Platform/RegisterModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).RegisterModule(ctx, req.(*Module))
	}
	return interceptor(ctx, in, info, handler)
}

var _Platform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModule",
			Handler:    _Platform_RegisterModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modularPlatform.proto",
}

func init() { proto.RegisterFile("modularPlatform.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x86, 0xb7, 0xbb, 0xa5, 0xed, 0xce, 0xa1, 0x42, 0x40, 0x08, 0x3d, 0x88, 0xd4, 0x8b, 0xa7,
	0x1e, 0xec, 0x03, 0x78, 0xd0, 0xab, 0x20, 0x7d, 0x83, 0x68, 0x47, 0x29, 0x24, 0x99, 0x32, 0x4d,
	0x7d, 0x7e, 0x69, 0xd2, 0x8a, 0xb7, 0xff, 0xfb, 0x12, 0x66, 0xfe, 0x81, 0xb5, 0xa1, 0x76, 0xd4,
	0x8a, 0xaf, 0x5a, 0xb9, 0x07, 0xb1, 0xa9, 0x7a, 0x26, 0x47, 0x22, 0x19, 0x90, 0x5f, 0xc8, 0xa5,
	0x86, 0xe4, 0x32, 0x7d, 0x40, 0x21, 0x20, 0xb6, 0xca, 0xa0, 0x8c, 0xb6, 0xd1, 0xfe, 0xbf, 0xf1,
	0x79, 0x72, 0x3d, 0xb1, 0x93, 0xbf, 0xc1, 0x4d, 0x59, 0x14, 0x90, 0x69, 0xba, 0x2b, 0xd7, 0x91,
	0x95, 0x7f, 0xde, 0x7f, 0x58, 0x6c, 0x00, 0x78, 0xb4, 0x27, 0x32, 0x46, 0xd9, 0x56, 0xc6, 0xfe,
	0xf5, 0xcb, 0x94, 0x3b, 0x48, 0xcf, 0xe8, 0x54, 0xa7, 0x07, 0x21, 0x21, 0x6d, 0x43, 0x9c, 0x37,
	0x2e, 0x78, 0x38, 0x42, 0xb6, 0x94, 0x15, 0x35, 0xe4, 0x0d, 0x3e, 0xbb, 0xc1, 0x21, 0xcf, 0x35,
	0xf3, 0x2a, 0x34, 0xaf, 0x02, 0x17, 0xab, 0x85, 0xe7, 0xc1, 0xe5, 0xcf, 0x2d, 0xf1, 0x27, 0xd6,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x20, 0xb9, 0xd4, 0xfb, 0x00, 0x00, 0x00,
}
